### ISSUE TITLE
Enlace: Allow one user access to many programs

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/lisc-ttm#121]
See https://github.com/OpenTechStrategies/lisc-ttm/issues/78#issuecomment-61672211.

@kevinrak9 just reminded us that this is something a lot of their users want and need.  @cwebber is designing the #78 API to be compatible with this change.

**Comment by cwebber** [comment]
Migration script seems to work, updating auth.php to deal with it appropriately next

**Comment by cwebber** [comment]
I accidentally committed some stuff to master instead of the #121 branch, but I've fixed both the branch and master.

**Comment by cwebber** [comment]
So, I believe I've made the appropriate edits to the 121 branch, but I haven't tested it yet.  I started to, but then I found that the code didn't seem to be working... looks like there's been a major schema change with master!  I'll have to update my database to make sure things are working with both.  But that'll happen tomorrow.

**Comment by cwebber** [comment]
I decided to do a test with the old user_debug_demo.php I wrote for #78 and see if the "admin" user from the demo site was still able to access the same things I had in there.

It doesn't seem so, though why this is I haven't determined.  Here are some of the old tests:

``` php
        echo("<p>Past the basic checks, now let's try some subsites and stuff...</p>");
        echo("TRP w/ access level 1 and program access 'b'<br/>");
        user_enforce_has_access($TRP_id, 1, "b", $fake_die_unauthorized);
        echo("SWOP w/ access level 2 and program access 'g'<br/>");
        user_enforce_has_access($SWOP_id, 2, "g", $fake_die_unauthorized);
        echo("Enlace w/ access level 3 and no program access check<br/>");
        user_enforce_has_access($Enlace_id, 3, NULL, $fake_die_unauthorized);
        echo("Enlace w/ no access level check an program access 'b'<br/>");
        user_enforce_has_access($Enlace_id, NULL, "b", $fake_die_unauthorized);
        echo("<p>Okay, that's enough :)</p>");
```

Old output:

```
TRP w/ access level 1 and program access 'b'
SWOP w/ access level 2 and program access 'g'
*SIREN NOISE! SIREN NOISE!* Failed check, imagine we blew up with the message: Sorry! You don't have permission to access this page. Please contact your site administrator for more information.
Enlace w/ access level 3 and no program access check
Enlace w/ no access level check an program access 'b'
*SIREN NOISE! SIREN NOISE!* Failed check, imagine we blew up with the message: Sorry! You don't have permission to access this page. Please contact your site administrator for more information.
```

New output:

```
TRP w/ access level 1 and program access 'b'
*SIREN NOISE! SIREN NOISE!* Failed check, imagine we blew up with the message: Sorry! You don't have permission to access this page. Please contact your site administrator for more information.
SWOP w/ access level 2 and program access 'g'
*SIREN NOISE! SIREN NOISE!* Failed check, imagine we blew up with the message: Sorry! You don't have permission to access this page. Please contact your site administrator for more information.
Enlace w/ access level 3 and no program access check
Enlace w/ no access level check an program access 'b'
*SIREN NOISE! SIREN NOISE!* Failed check, imagine we blew up with the message: Sorry! You don't have permission to access this page. Please contact your site administrator for more information. 
```

Why do none of these work with the new structure?  This should be resolved before we go live.

**Comment by cwebber** [comment]
Upon further investigation, it actually looks like the new code is doing what is expected.  Sorry, I spent some time on this but I wanted to thoroughly check that our new code would not cause regressions.  Here is why both our new code and the old code are simultaneously correct, despite the difference in program access 'b': program 'b' never existed, and thus the reason the old verison passed was because it had the old (and now deprecated) 'a' slot, which means it could access anything (seemingly, even things that did not exist).  Now we give users who used to have 'a' access to all *currently existing* programs for this subsite.  Since 'b' does not exist, the new code is also behaving correctly, since it sees there is no such program in that list.

**Comment by cwebber** [comment]
I did testing against things that should and should not allow access and have verified that this overhaul seems to be working right here.  Yay!

Next up, do the merge with master, switch my own database over.

**Comment by cwebber** [comment]
@cecilia-donnelly I think there's a problem with the "lock" migration script... it asks to drop the Locked column before it creates it, but the Locked column doesn't exist.  Was this dropping a preliminary / testing version of the Locked column?

**Comment by cwebber** [comment]
Merged in master.  After making that Locked change things seem to work fine!

**Comment by cecilia-donnelly** [comment]
@cwebber you're right, I should have skipped that line dropping the column.  I was thinking of the "drop table if exists" precaution, but a similar test doesn't seem to exist for columns.

Thanks for the careful testing of the new functions and schema!

**Comment by cecilia-donnelly** [comment]
Merged to master and deployed to prod today, [2015-05-16].
