### ISSUE TITLE
Enlace: can't delete participants

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/lisc-ttm#156]
@kevinrak9 reports:

>After adding both the participants to a program, I tried to delete one using the red X. Aside from a small bar on the bottom left saying something like "javascript:;" nothing happened, the duplicate participants remained. 

Kevin sent me a screenshot, which I've cropped to just the console errors (see below).  Essentially, we're talking about the top-level "Participants" page, where he searched for a participant by first and last name.  He got two versions of the same person (with the same birthday) and could see the "delete" button correctly.  Having the console errors will help track this down.  Thanks, @kevinrak9!

<img width="1327" alt="deletion_console_errors" src="https://cloud.githubusercontent.com/assets/1497818/11546186/43ccd024-9911-11e5-8d6a-fc0e10cbd619.png">

**Comment by cecilia-donnelly** [comment]
Tested and fix is working on prod mirror server.

**Comment by cecilia-donnelly** [comment]
Deployed to prod.  @kevinrak9, let me know if this is working now.

**Comment by kevinrak9** [comment]
@cecilia-donnelly I tested, and was able to delete a duplicate participant from the database completely. Thanks!

**Comment by cecilia-donnelly** [comment]
Great, thanks!!
