### ISSUE TITLE
Enlace: remove homepage alerts

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/lisc-ttm#157]
- not working as intended (very old alerts remain)
- privacy issue (all users can see all youth alerts)
- this _might_ be useful if it offered search by program and date,
   but even so it's a low priority

**Comment by kevinrak9** [comment]
This looks great, thanks!

**Comment by cecilia-donnelly** [comment]
Deployed on [2016-01-14].
