### ISSUE TITLE
Enlace: participant DOB can't be edited

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/lisc-ttm#158]
Saving other changes in the general info box works, but the DOB disappears whenever any change to anything is made.  Should be a quick fix.  I've already reproduced it on my local copy.

**Comment by kevinrak9** [comment]
I tested and it works, both manually putting in the date, and selecting from the calendar pop-up.

**Comment by cecilia-donnelly** [comment]
Deployed on [2016-01-14].
