### ISSUE TITLE
Enlace: order attendance dates in descending order

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/lisc-ttm#159]
- currently entering attendance takes way too much scrolling
- switch dates to DESC instead of ASC as a quick fix

**Comment by kevinrak9** [comment]
This is great! Let me know as soon as you deploy this, because I'll notify data entry users right away.

**Comment by cecilia-donnelly** [comment]
@kevinrak9 I just deployed this (and the other fixes), so go ahead and notify the users.
