### ISSUE TITLE
Enlace - date format causing participant profile to load incorrectly

### ISSUE THREAD

**Issue by kevinrak9** [OpenTechStrategies/lisc-ttm#170]
Per Karl's request, here is the issue I submitted to ttmhelp@opentechstrategies.com last week. 

There was a participant whose profile was not loading correctly. From my email: "The contact information box that should only take up the top left corner stretched across the page, and no other information displayed (i.e., notes, program involvement, etc. - see attached screenshot). I know this youth is enrolled in a program because I clicked on their name from the Saint Anthony Family Support Groups program page. They are also listed as a youth/student, so we should be seeing a larger profile for them." 

This was the only participant profile having this issue, as far as I could tell. 

@cecilia-donnelly looked into it and identified: "This should be fixed now.  Let me know if you continue to see this problem, of course.  It looks like his birthday was entered as 2005-14-06 and the code didn't recognize that as a valid date and so stopped loading the page.  I've edited it so that it just displays the date differently and doesn't break."

I have since edited this participant's birthdate to YYYY-MM-DD format. 

She added: "I didn't add any kind of flag/warning for users, though.  Do you think you might want a message there that says, "Hey, doublecheck this date"?" 

I agreed. @kfogel suggested not allowing users to enter an invalid date. 

Going forward, I think it would be good to do both: show an error message if an invalid date is entered, and not allow the edit to be saved until a valid date is entered. 

Thanks!

**Comment by kevinrak9** [comment]
@cecilia-donnelly I don't know the code well enough to understand exactly how it will work, but thanks for doing this! I think preventing invalid dates from being saved would help increase data quality, so that would be good to add.

**Comment by cecilia-donnelly** [comment]
@kevinrak9 looked at this and suggested:

[ ] allow users to input dates as MM-DD-YYYY
[ ] show an error near the "save" button, instead of only near the dob input.

**Comment by cecilia-donnelly** [comment]
Test cases:
- [ ] No date
   - Result: save successfully
- [ ] Valid date in MM-DD-YYYY format
   - Result: save successfully
- [ ] Valid date format for a nonexistent date (e.g. 02-30-2016)
   - Result: error
- [ ] Valid date in some other format (e.g. YYYY-MM-DD or DD-MM-YYYY)
   - Result: error
- [ ] Invalid date like 10-0-2016
   - Result: error

**Comment by kfogel** [comment]
How can one reliably distinguish between MM-DD-YYYY and DD-MM-YYYY?

**Comment by cecilia-donnelly** [comment]
@kfogel We can't distinguish most of the time, but we expect the date to be entered in MM-DD-YYYY.  If someone entered August 6th, 2016 as 6-8-2016 then we'd misinterpret it as June 8th, 2016.  My test case referred to something like 31-12-2015, which would get an error.

I *think* that's all we can do.  Do you have other ideas?

**Comment by cecilia-donnelly** [comment]
Deployed on [2016-11-3].
