### ISSUE TITLE
Enlace: Increase Grade Tracked

### ISSUE THREAD

**Issue by frankduncan** [OpenTechStrategies/lisc-ttm#188]
Database tracks 5th-8th. This should be extended to 9th.
Enlace Note: Everywhere there exists a dropdown for grade, the option to choose 9th grade should be present

**Comment by easherma** [comment]
@fogel did you want me to submit my pull request that addresses this issue?

**Comment by cecilia-donnelly** [comment]
Ping @kfogel.

**Comment by kfogel** [comment]
@easherma sure, thank you!

**Comment by frankduncan** [comment]
Hey @easherma, I also have a fix that I'm pushing to my test server for enlace to look at.  If you submit a PR this week, I'll push it to the server as a merge with mine (hopefully with zero actual merging) and have them look it over :)
