### ISSUE TITLE
Enlace - Intake association date

### ISSUE THREAD

**Issue by frankduncan** [OpenTechStrategies/lisc-ttm#219]
In an effort to not give youth who are enrolled in concurrent programming, intake surveys are duplicated. There currently exists some mechanic. This mechanic can be improved by having this duplication take the date of session start.

The mechanic of duplicating an intake survey should take the session start date as opposed as the date logged or the date entered

**Comment by kfogel** [comment]
This is a use of the word "mechanic" I'm not familiar with -- is it a term of art in PHP?

**Comment by frankduncan** [comment]
That was copied/pasted from the requirements document.  I think it probably should have been mechanics?

**Comment by kfogel** [comment]
Or "mechanism" maybe?

**Comment by frankduncan** [comment]
This feature was decided to be unneeded complete (#240), and thus this bug is no longer valid.
