### ISSUE TITLE
Enlace: Add survey entry point link that doesn't require login

### ISSUE THREAD

**Issue by frankduncan** [OpenTechStrategies/lisc-ttm#221]
From Enlace:
> The TTM database should have a separate entry point where youth can answer and enter survey data. This separate entry point should be limited in function and ability.
>
> This data entry point should be found in each program page and, if possible, there should exist the ability to have multiple surveys filled out or at a minimum two entry points serving as pre or post entries.

We'll do this by creating a hash on the participant id, session id, and participant name + a secret key, and then require that no survey has been filled out that matches those, and that the hash is valid,and provide that link in the program page for people to copy/paste into emails for youths to enter their surveys

**Comment by kfogel** [comment]
*nod*  @frankduncan, remind me to make sure we record the salt (the secret key) in the appropriate out-of-band encrypted vault.

**Comment by frankduncan** [comment]
Based on the review in #248, change this to create a short code (base32: https://en.wikipedia.org/wiki/Base32) that encodes the intake/impact, participant id, and session_ID, as well as subsequence of the sha that's generated.  This can be input at the login screen instead of regular login information (as well as have a link).

For space purposes on the participant table, have a popup box with the information and instructions.

**Comment by frankduncan** [comment]
After going down this implementation path some, the complexity of the code was too great, so moving to a simple generated code can be used and stored in a new Assessments_Codes table.  Generate the code when a user clicks on the "link" link that will provide a popup.
