### ISSUE TITLE
Apache error log showing "undefined index" errors on login and logout.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/lisc-ttm#27]
I was logged into production as vrizzi, and when I logged out, /var/log/apache2/ttm_error.log showed exactly these two errors (note that the path given in the first error is just the page where I happened to be when I logged out -- that's not part of this bug report):

    [Fri Jun 27 20:25:27 2014] [error] [client 74.92.190.113] PHP Notice:  Undefined index: sites in /var/www/ttm/trp/header.php on line 37, referer: https://ttm.lisc-chicago.org/trp/participants/profile.php?id=374
    [Fri Jun 27 20:25:27 2014] [error] [client 74.92.190.113] PHP Notice:  Undefined index: action in /var/www/ttm/index.php on line 3, referer: https://ttm.lisc-chicago.org/trp/participants/profile.php?id=374

And if I log *in* as vrizzi, it shows the second type of error too:

    [Fri Jun 27 20:27:40 2014] [error] [client 74.92.190.113] PHP Notice:  Undefined index: action in /var/www/ttm/index.php on line 3, referer: https://ttm.lisc-chicago.org/index.php

Similar behavior has been seen on the dev server, and with other users -- I'm just using vrizzi as an example.

**Comment by cecilia-donnelly** [comment]
See pull request #135.  In brief, I'm closing this because the relevant lines are no longer in master.
