### ISSUE TITLE
Make a robots.txt file, to block cooperative crawlers.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/lisc-ttm#28]
We don't have a robots.txt file yet.  I suspect that's why we see things like, e.g., this in /var/log/apache2/ttm_error.log:

    [Fri Jun 27 20:26:14 2014] [error] [client 75.168.181.198] File does not exist: /var/www/ttm/EWS
    [Fri Jun 27 20:26:14 2014] [error] [client 75.168.181.198] File does not exist: /var/www/ttm/EWS
    [Fri Jun 27 20:26:14 2014] [error] [client 75.168.181.198] File does not exist: /var/www/ttm/EWS
    [Fri Jun 27 20:26:15 2014] [error] [client 75.168.181.198] File does not exist: /var/www/ttm/EWS
    [Fri Jun 27 20:26:25 2014] [error] [client 75.168.181.198] File does not exist: /var/www/ttm/EWS
    [Fri Jun 27 20:26:55 2014] [error] [client 24.52.219.245] File does not exist: /var/www/ttm/autodiscover

We should have a standard robots.txt, obviously.

**Comment by cecilia-donnelly** [comment]
Pulled this to production today and it seems to be working fine.  I did not make the changes to the apache config file recommended in INSTALL.md.
